language: android
jdk: oraclejdk8
sudo: true
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
before_install:
  - yes | sdkmanager "platforms;android-28"
script: ./gradlew clean lint test
after_success: ./deploy_snapshot.sh
